CREATE TABLE User (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	pseudo VARCHAR(40) NOT NULL,
	password VARCHAR(40) NOT NULL,
	name VARCHAR(40) NOT NULL,
	first_name VARCHAR(40) NOT NULL,
	email VARCHAR(100) NOT NULL,
	status_owner VARCHAR(10) NOT NULL,
	phone VARCHAR(40) NOT NULL,
	PRIMARY KEY (id)
)
ENGINE=INNODB;


CREATE TABLE User (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (id)
)
ENGINE=INNODB;