CREATE TABLE User (
	id_user SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	pseudo VARCHAR(40) NOT NULL,
	password VARCHAR(40) NOT NULL,
	name VARCHAR(40) NOT NULL,
	first_name VARCHAR(40) NOT NULL,
	email VARCHAR NOT NULL,
	status VARCHAR(10) NOT NULL,
	phone VARCHAR(40) NOT NULL,
	PRIMARY KEY (id_user)
)
ENGINE=INNODB;
